# -*- coding: utf-8 -*-
"""0-9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYZk4dMRYEicLJLv6XhBSBidbDHx4mt3
"""

import zipfile
import os
import pathlib
import matplotlib.pyplot as plt


zip_path = "/content/archive (2).zip"


extract_path = "/content/"
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)


data_dir = pathlib.Path("/content/num/")


print(f"✅ Extrac suc {len(os.listdir(data_dir))} file (0-9)")

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split


image_paths = []
labels = []

for label in sorted(os.listdir(data_dir)):
    label_path = os.path.join(data_dir, label)
    if os.path.isdir(label_path):
        for image_file in os.listdir(label_path):
            image_paths.append(os.path.join(label_path, image_file))
            labels.append(int(label))


train_paths, test_paths, train_labels, test_labels = train_test_split(
    image_paths, labels, test_size=0.2, random_state=42, stratify=labels
)

def load_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_png(img, channels=1)
    img = tf.image.resize(img, [28, 28])
    img = img / 255.0
    return img

train_ds = tf.data.Dataset.from_tensor_slices((train_paths, train_labels))
train_ds = train_ds.map(lambda x, y: (load_image(x), y)).batch(32)

test_ds = tf.data.Dataset.from_tensor_slices((test_paths, test_labels))
test_ds = test_ds.map(lambda x, y: (load_image(x), y)).batch(32)

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_ds, epochs=10, validation_data=test_ds)

loss, acc = model.evaluate(test_ds)
print(f"Test Accuracy: {acc * 100:.2f}%")

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()

# 📌 บันทึกโมเดลเป็นไฟล์ .h5
model.save("/content/digit_classifier.h5")
print("✅ โมเดลถูกบันทึกแล้ว!")

from google.colab import files

# 📌 ดาวน์โหลดไฟล์โมเดลไปยังเครื่องของคุณ
files.download("/content/digit_classifier.h5")

import matplotlib.pyplot as plt

# 📌 แสดงกราฟ Loss และ Accuracy
# กราฟ Loss
plt.figure(figsize=(12, 6))

# Subplot สำหรับ Loss
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Train Loss', color='blue')
plt.plot(history.history['val_loss'], label='Validation Loss', color='red')
plt.title('Loss over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

# Subplot สำหรับ Accuracy
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Train Accuracy', color='blue')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='red')
plt.title('Accuracy over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# แสดงกราฟทั้งหมด
plt.tight_layout()
plt.show()